description: >
  This is a sample executor using Docker and Node.
docker:
  - image: 'cimg/php:<<parameters.tag>>'
parameters:
  tag:
    default: 8.1
    description: >
      Pick a specific cimg/node image variant:
      https://hub.docker.com/r/cimg/node/tags
    type: string
