version: 2.1

setup: true

orbs:
  orb-tools: circleci/orb-tools@11.3.0
  shellcheck: circleci/shellcheck@3.1

filters: &filters
  tags:
    only: /.*/

matrix: &projects
  parameters:
    name: ['prettier']

workflows:
  main:
    jobs:
      - orb-tools/lint:
          name: << matrix.name >>/lint
          filters: *filters
          matrix: *projects
          source-dir: << matrix.name >>/src/
      - orb-tools/pack:
          name: << matrix.name >>/pack
          filters: *filters
          matrix: *projects
          source-dir: << matrix.name >>/src/
          output-dir: << matrix.name >>/dist/
      - orb-tools/review:
          name: << matrix.name >>/review
          filters: *filters
          matrix: *projects
          source-dir: << matrix.name >>/src/
      - shellcheck/check:
          name: << matrix.name >>/shellcheck
          filters: *filters
          matrix: *projects
          dir: << matrix.name >>
      - orb-tools/publish:
          name: << matrix.name >>/publish
          orb-name: syneki/<< matrix.name >>
          orb-dir: << matrix.name >>/dist/
          vcs-type: << pipeline.project.type >>
          requires:
            [
              << matrix.name >>/lint,
              << matrix.name >>/review,
              << matrix.name >>/pack,
              << matrix.name >>/shellcheck,
            ]
          context: orb-publishing
          filters: *filters
          matrix: *projects
      - orb-tools/continue:
          name: << matrix.name >>/continue
          pipeline-number: << pipeline.number >>
          vcs-type: << pipeline.project.type >>
          requires: [<< matrix.name >>/publish]
          config-path: << matrix.name >>/.circleci/config.yml
          filters: *filters
          matrix: *projects
