version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.1.3

workflows:
  main:
    jobs:
      - path-filtering/filter:
          base-revision: main
          config-path: docker/.circleci/config.yml
          workspace_path: docker
          mapping: |
            docker/.* build true