version: 2.1

setup: true

orbs:
  orb-tools: circleci/orb-tools@11.3.0

filters: &filters
  tags:
    only: /.*/

matrix: &projects
  parameters:
    projects: ['docker']

workflows:
  main:
    jobs:
      - orb-tools/lint:
          name: lint-<< matrix.project >>
          filters: *filters
          matrix: *projects
          source-dir: << matrix.project >>/src/
      - orb-tools/pack:
          name: pack-<< matrix.project >>
          filters: *filters
          matrix: *projects
          source-dir: << matrix.project >>/src/
          output-dir: << matrix.project >>/dist/
      - orb-tools/review:
          name: review-<< matrix.project >>
          filters: *filters
          matrix: *projects
          source-dir: << matrix.project >>/src/
      - shellcheck/check:
          name: shellcheck-<< matrix.project >>
          filters: *filters
          matrix: *projects
          dir: << matrix.project >>
      - orb-tools/publish:
          name: publish-<< matrix.project >>
          orb-name: syneki/<< matrix.project >>
          vcs-type: << pipeline.project.type >>
          requires:
            [lint-<< matrix.project >>, review-<< matrix.project >>, pack-<< matrix.project >>, shellcheck-<< matrix.project >>]
          context: orb-publishing
          filters: *filters
          matrix: *projects
      - orb-tools/continue:
          pipeline-number: << pipeline.number >>
          orb-dir: << matrix.project >>/dist/
          vcs-type: << pipeline.project.type >>
          requires: [publish-<< matrix.project >>]
          config-path: << matrix.project >>/.circleci/test.yml
          filters: *filters
          matrix: *projects