version: 2.1

setup: true

orbs:
  orb-tools: circleci/orb-tools@11.3.0
  shellcheck: circleci/shellcheck@3.1

filters: &filters
  tags:
    only: /.*/

matrix: &projects
  parameters:
    name: ['docker']

workflows:
  main:
    jobs:
      - orb-tools/lint:
          name: lint-<< matrix.name >>
          filters: *filters
          matrix: *projects
          source-dir: << matrix.name >>/src/
      - orb-tools/pack:
          name: pack-<< matrix.name >>
          filters: *filters
          matrix: *projects
          source-dir: << matrix.name >>/src/
          output-dir: << matrix.name >>/dist/
      - orb-tools/review:
          name: review-<< matrix.name >>
          filters: *filters
          matrix: *projects
          source-dir: << matrix.name >>/src/
      - shellcheck/check:
          name: shellcheck-<< matrix.name >>
          filters: *filters
          matrix: *projects
          dir: << matrix.name >>
      - orb-tools/publish:
          name: publish-<< matrix.name >>
          orb-name: syneki/<< matrix.name >>
          orb-dir: << matrix.name >>/dist/
          vcs-type: << pipeline.project.type >>
          requires:
            [lint-<< matrix.name >>, review-<< matrix.name >>, pack-<< matrix.name >>, shellcheck-<< matrix.name >>]
          context: orb-publishing
          filters: *filters
          matrix: *projects
      - orb-tools/continue:
          pipeline-number: << pipeline.number >>
          vcs-type: << pipeline.project.type >>
          requires: [publish-<< matrix.name >>]
          config-path: << matrix.name >>/.circleci/test.yml
          filters: *filters
          matrix: *projects