version: 2.1

description: >
  This orb provide powerfull features to work with Docker.
  Fetching tags, creating matrix, etc.

display:
  home_url: "https://github.com/syneki/circleci-orbs"
  source_url: "https://github.com/syneki/circleci-orbs"
