version: 2.1

description: >
  An util orb for creating powerfull Docker pipelines

display:
  home_url: "https://github.com/syneki/circleci-orbs"
  source_url: "https://github.com/syneki/circleci-orbs/docker"
